import { createGetHandler, createPostHandler } from '$lib/server/api-helpers.js';
import { decodeJson } from '$lib/server/db/index.js';

function decodeRow(row: Record<string, unknown>) {
	return {
		...row,
		aliases: decodeJson<string[]>(row.aliases as string),
		anomalies: decodeJson<string[]>(row.anomalies as string),
		traits: decodeJson<string[]>(row.traits as string),
		goals: decodeJson<string[]>(row.goals as string),
		flaws: decodeJson<string[]>(row.flaws as string),
		arcs: decodeJson<string[]>(row.arcs as string),
		tags: decodeJson<string[]>(row.tags as string),
	};
}

const config = {
	table: 'characters',
	fields: {
		projectId: { required: true },
		name: { required: true },
		role: { default: '' },
		occupation: { default: '' },
		age: { default: '' },
		height: { default: '' },
		weight: { default: '' },
		build: { default: '' },
		hair: { default: '' },
		eyes: { default: '' },
		coreDesire: { default: '' },
		fear: { default: '' },
		contradiction: { default: '' },
		temperament: { default: '' },
		alignment: { default: '' },
		strength: { default: '' },
		flaw: { default: '' },
		storyRole: { default: '' },
		arcStage: { default: '' },
		externalGoal: { default: '' },
		internalNeed: { default: '' },
		stakes: { default: '' },
		conflict: { default: '' },
		voiceSummary: { default: '' },
		speechPattern: { default: '' },
		phrases: { default: '' },
		tells: { default: '' },
		bodyLanguage: { default: '' },
		dialogueSample: { default: '' },
		immutableTraits: { default: '' },
		injuries: { default: '' },
		habits: { default: '' },
		secrets: { default: '' },
		othersKnow: { default: '' },
		lastChange: { default: '' },
		timelineMarkers: { default: '' },
		emotionalState: { default: '' },
		currentObjective: { default: '' },
		currentPressure: { default: '' },
		lastSeen: { default: '' },
		nextMove: { default: '' },
		pronunciation: { default: '' },
		aliases: { default: [], json: true },
		diasporaOrigin: { default: '' },
		photoUrl: { default: '' },
		bio: { default: '' },
		faction: { default: '' },
		anomalies: { default: [], json: true },
		traits: { default: [], json: true },
		goals: { default: [], json: true },
		flaws: { default: [], json: true },
		arcs: { default: [], json: true },
		notes: { default: '' },
		tags: { default: [], json: true },
	},
	orderBy: 'createdAt ASC',
	queryParams: ['projectId'],
	decodeRow,
};

export const GET = createGetHandler(config);
export const POST = createPostHandler(config);
