/**
 * Proposal record schema for the agentic worldbuild scan feature (plan-037).
 *
 * A proposal represents a single non-canonical suggestion generated by a
 * worldbuild scan. It remains non-canonical until the author explicitly
 * accepts it. Rejected proposals never write to canon.
 *
 * This schema is complementary to the existing CheckpointRecord — proposals
 * are lighter scan outputs, not full domain-pipeline checkpoints.
 */

import type { WorldbuildingDomainId } from '../../../modules/world-building/worldbuilding-workflow.js';

// ---------------------------------------------------------------------------
// Status lifecycle
// ---------------------------------------------------------------------------

export type WorldbuildProposalStatus =
	| 'pending_review'
	| 'accepted'
	| 'rejected'
	| 'failed_validation';

export const PROPOSAL_STATUS_ORDER: readonly WorldbuildProposalStatus[] = [
	'pending_review',
	'accepted',
	'rejected',
	'failed_validation',
] as const;

export function isWorldbuildProposalStatus(value: unknown): value is WorldbuildProposalStatus {
	return typeof value === 'string' && PROPOSAL_STATUS_ORDER.includes(value as WorldbuildProposalStatus);
}

// ---------------------------------------------------------------------------
// Source context snapshot stored with each proposal
// ---------------------------------------------------------------------------

/**
 * Compact snapshot of project context at scan time. Stored for auditability
 * so reviewers know what context produced the suggestion.
 *
 * `synopsisHash` is a short stable identifier (e.g. first 8 chars of a
 * deterministic hash) — never the full synopsis text, which may change.
 */
export interface WorldbuildProposalSourceContext {
	title: string;
	genre: string;
	logline: string;
	/** Short stable identifier derived from synopsis at scan time. */
	synopsisHash: string;
}

// ---------------------------------------------------------------------------
// Audit metadata
// ---------------------------------------------------------------------------

export interface WorldbuildProposalAcceptance {
	acceptedAt: string;
	acceptedBy: string | null;
	/** Projection target — which canon table/service received the entity. */
	projectionTarget: string;
	/** Whether the projection completed without error. */
	projectedToCanon: boolean;
}

export interface WorldbuildProposalRejection {
	rejectedAt: string;
	rejectedBy: string | null;
	/** Optional free-text reason from the author. */
	reason: string;
}

// ---------------------------------------------------------------------------
// Full proposal record
// ---------------------------------------------------------------------------

/**
 * A single non-canonical worldbuilding suggestion produced by an agentic scan.
 *
 * Field notes:
 * - `proposalId` — stable UUID, assigned at generation time
 * - `categoryId` — which worldbuilding domain this suggestion belongs to
 * - `entityKind` — specific entity type within the category (e.g. 'character' within 'personae')
 * - `confidence` — bounded 0–1 score; interpretation is heuristic, not guaranteed
 * - `reasoningSummary` — one-sentence model explanation for why this suggestion was produced
 * - `dedupeKey` — deterministic string used to suppress near-duplicate proposals
 * - `payload` — category-specific draft data; shape validated before persistence
 */
export interface WorldbuildProposalRecord {
	proposalId: string;
	projectId: string;
	categoryId: WorldbuildingDomainId;
	entityKind: string;
	status: WorldbuildProposalStatus;
	generatedAt: string;
	sourceContext: WorldbuildProposalSourceContext;
	/** Heuristic confidence, clamped 0–1. Treat as an ordering signal, not a guarantee. */
	confidence: number;
	reasoningSummary: string;
	/** Validated draft payload. Shape depends on entityKind. */
	payload: Record<string, unknown>;
	dedupeKey: string;
	acceptance: WorldbuildProposalAcceptance | null;
	rejection: WorldbuildProposalRejection | null;
}

// ---------------------------------------------------------------------------
// Dedupe key construction
// ---------------------------------------------------------------------------

/**
 * Build a deterministic dedupe key from category, entity kind, and primary
 * identifier (name or title). Lowercased and whitespace-collapsed for
 * normalization.
 *
 * Format: `{categoryId}:{entityKind}:{normalizedIdentifier}`
 *
 * Example: `personae:character:elara voss`
 *
 * Callers should compare new proposals against existing pending proposals
 * AND existing canon before persisting.
 */
export function buildProposalDedupeKey(
	categoryId: WorldbuildingDomainId,
	entityKind: string,
	primaryIdentifier: string,
): string {
	const normalized = primaryIdentifier.trim().toLowerCase().replace(/\s+/g, ' ');
	return `${categoryId}:${entityKind}:${normalized}`;
}

/**
 * Check whether a candidate dedupe key collides with any key in the provided
 * set. The comparison is exact after normalization — semantic duplicates
 * beyond name-matching are out of scope for this layer.
 *
 * For semantic near-duplicates, the `reasoningSummary` field should be used
 * during manual review to detect overlap that name matching misses.
 */
export function isDuplicateProposalKey(
	candidateKey: string,
	existingKeys: ReadonlySet<string>,
): boolean {
	return existingKeys.has(candidateKey);
}

// ---------------------------------------------------------------------------
// Proposal validation helpers
// ---------------------------------------------------------------------------

/** Minimum confidence threshold below which proposals should be omitted. */
export const MIN_PROPOSAL_CONFIDENCE = 0.2;

/** Maximum proposals returned per scan run. */
export const MAX_PROPOSALS_PER_SCAN = 5;

/**
 * Clamp a raw confidence value to the valid [0, 1] range.
 * The model may emit values slightly outside this range due to floating-point.
 */
export function clampConfidence(raw: number): number {
	return Math.min(1, Math.max(0, raw));
}
